name: final_student_dashboard
description: A student dashboard application for quizzes is a software tool that allows students to view their quiz results and progress in one place

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  get: ^4.6.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.4
  device_preview: ^1.1.0
  flutter_zoom_drawer: ^3.0.3
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^4.7.0

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
